name: Docker Image CI

on:
  push:
    branches: [ "main", "master" ] # Triggers the workflow on pushes to main or master branch
  pull_request:
    branches: [ "main", "master" ] # Triggers the workflow on pull requests to main or master branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Specifies the runner environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # Checks out your repository code

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }} # Uses the GitHub secret for Docker Hub username
        password: ${{ secrets.DOCKER_PASSWORD }} # Uses the GitHub secret for Docker Hub password

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: tslowikowski/gitopshook # Replace with your Docker Hub username and repository name
        tags: |
          type=raw,value=latest,enable={{is_default_branch}} # Tags the image as 'latest' for default branch
          type=ref,event=branch # Tags with branch name
          type=sha # Tags with commit SHA

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: . # Specifies the build context (current directory)
        push: true # Pushes the image to the registry
        tags: ${{ steps.meta.outputs.tags }} # Uses the tags generated by the metadata action
        labels: ${{ steps.meta.outputs.labels }} # Uses the labels generated by the metadata action
        file: ./Dockerfile # Specifies the path to your Dockerfile